scp -r /c16/THESE.JORIS/datasets/NYUD_V2/data/rgb_i_10_8bits jogue@pc.jorisguerry.fr:/data/workspace/datasets/NYUD_V2/data/
scp -r /c16/THESE.JORIS/datasets/NYUD_V2/data/rgb_i_20_8bits jogue@pc.jorisguerry.fr:/data/workspace/datasets/NYUD_V2/data/
scp -r /c16/THESE.JORIS/datasets/NYUD_V2/data/rgb_i_30_8bits jogue@pc.jorisguerry.fr:/data/workspace/datasets/NYUD_V2/data/
scp -r /c16/THESE.JORIS/datasets/NYUD_V2/data/rgb_i_40_8bits jogue@pc.jorisguerry.fr:/data/workspace/datasets/NYUD_V2/data/
scp -r /c16/THESE.JORIS/datasets/NYUD_V2/data/rgb_i_50_8bits jogue@pc.jorisguerry.fr:/data/workspace/datasets/NYUD_V2/data/
scp -r /c16/THESE.JORIS/datasets/NYUD_V2/data/rgb_i_60_8bits jogue@pc.jorisguerry.fr:/data/workspace/datasets/NYUD_V2/data/
scp -r /c16/THESE.JORIS/datasets/NYUD_V2/data/rgb_i_70_8bits jogue@pc.jorisguerry.fr:/data/workspace/datasets/NYUD_V2/data/
scp -r /c16/THESE.JORIS/datasets/NYUD_V2/data/rgb_i_80_8bits jogue@pc.jorisguerry.fr:/data/workspace/datasets/NYUD_V2/data/
scp -r /c16/THESE.JORIS/datasets/NYUD_V2/data/rgb_i_90_8bits jogue@pc.jorisguerry.fr:/data/workspace/datasets/NYUD_V2/data/
