function plotOfRepartsTestGuptaNYUDV2(yvector1)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 19-Dec-2016 18:50:33

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'bag','bathtub','bed','blinds','books','bookshelf','box','cabinet','ceiling','chair','clothes','counter','curtain','desk','door','dresser','floor','floor mat','lamp','mirror','night stand','otherfurniture','otherprop','otherstructure','paper','person','picture','pillow','refridgerator','shelves','shower curtain','sink','sofa','table','television','toilet','towel','wall','whiteboard','window'},...
    'XTick',[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]);
box(axes1,'on');
hold(axes1,'all');

% Create bar
bar(yvector1);

